module.exports = {
  apps: [
    {
      name: "auth-service",
      cwd: "./auth-service",
      script: "app.js",
      env: {
        PORT: 5000,
        NODE_ENV: "production",
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "500M",
      error_file: "/usr/src/app/logs/auth-error.log",
      out_file: "/usr/src/app/logs/auth-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "book-service",
      cwd: "./book-service",
      script: "app.js",
      env: {
        PORT: 3000,
        NODE_ENV: "production",
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "500M",
      error_file: "/usr/src/app/logs/book-error.log",
      out_file: "/usr/src/app/logs/book-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "cart-service",
      cwd: "./cart-service",
      script: "src/app.js",
      env: {
        PORT: 3001,
        NODE_ENV: "production",
        BOOK_SERVICE_URL: "http://localhost:3000/api/books",
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "500M",
      error_file: "/usr/src/app/logs/cart-error.log",
      out_file: "/usr/src/app/logs/cart-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "order-service",
      cwd: "./order-service",
      script: "src/app.js",
      env: {
        PORT: 3002,
        NODE_ENV: "production",
        CART_SERVICE_URL: "http://localhost:3001/api",
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "500M",
      error_file: "/usr/src/app/logs/order-error.log",
      out_file: "/usr/src/app/logs/order-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "api-gateway",
      cwd: "./api-gateway",
      script: "src/server.js",
      env: {
        PORT: 3000,
        NODE_ENV: "production",
        REDIS_URL: "redis://localhost:6379",
        AUTH_SERVICE_URL: "http://localhost:5000",
        BOOK_SERVICE_URL: "http://localhost:3000",
        CART_SERVICE_URL: "http://localhost:3001",
        ORDER_SERVICE_URL: "http://localhost:3002",
        CORS_ORIGIN: "http://localhost:4200",
        LOG_LEVEL: "info",
      },
      instances: 1,
      exec_mode: "fork",
      watch: false,
      max_memory_restart: "500M",
      error_file: "/usr/src/app/logs/gateway-error.log",
      out_file: "/usr/src/app/logs/gateway-out.log",
      merge_logs: true,
      time: true,
    },
  ],
};
